## 12 MHz System Clock
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 83.330 -name sys_clk_pin -waveform {0.000 41.660} -add [get_ports clk]

## Because system clock is not on the correct pin
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

## USB UART
## Note: Port names are from the perspoctive of the FPGA.
#set_property -dict { PACKAGE_PIN F1   IOSTANDARD LVCMOS33 } [get_ports { uart_tx }]
#set_property -dict { PACKAGE_PIN G1   IOSTANDARD LVCMOS33 } [get_ports { uart_rx }]

## Cartridge ports
set_property -dict { PACKAGE_PIN P10   IOSTANDARD LVCMOS33 } [get_ports { gb_clk }]
set_property -dict { PACKAGE_PIN N10   IOSTANDARD LVCMOS33 } [get_ports { gb_wr }]
set_property -dict { PACKAGE_PIN P11   IOSTANDARD LVCMOS33 } [get_ports { gb_rd }]
set_property -dict { PACKAGE_PIN N11   IOSTANDARD LVCMOS33 } [get_ports { gb_cs }]
set_property -dict { PACKAGE_PIN P12   IOSTANDARD LVCMOS33 } [get_ports { gb_a[0] }]
set_property -dict { PACKAGE_PIN M12   IOSTANDARD LVCMOS33 } [get_ports { gb_a[1] }]
set_property -dict { PACKAGE_PIN P13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[2] }]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[3] }]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[4] }]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[5] }]
set_property -dict { PACKAGE_PIN L13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[6] }]
set_property -dict { PACKAGE_PIN L14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[7] }]
set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[8] }]
set_property -dict { PACKAGE_PIN J14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[9] }]
set_property -dict { PACKAGE_PIN H13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[10] }]
set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[11] }]
set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[12] }]
set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { gb_a[13] }]
set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[14] }]
set_property -dict { PACKAGE_PIN E13   IOSTANDARD LVCMOS33 } [get_ports { gb_a[15] }]
set_property -dict { PACKAGE_PIN D14   IOSTANDARD LVCMOS33 } [get_ports { gb_rst }]
set_property -dict { PACKAGE_PIN D13   IOSTANDARD LVCMOS33 } [get_ports { gb_d[0] }]
set_property -dict { PACKAGE_PIN C14   IOSTANDARD LVCMOS33 } [get_ports { gb_d[1] }]
set_property -dict { PACKAGE_PIN D12   IOSTANDARD LVCMOS33 } [get_ports { gb_d[2] }]
set_property -dict { PACKAGE_PIN B14   IOSTANDARD LVCMOS33 } [get_ports { gb_d[3] }]
set_property -dict { PACKAGE_PIN B13   IOSTANDARD LVCMOS33 } [get_ports { gb_d[4] }]
set_property -dict { PACKAGE_PIN C12   IOSTANDARD LVCMOS33 } [get_ports { gb_d[5] }]
set_property -dict { PACKAGE_PIN A13   IOSTANDARD LVCMOS33 } [get_ports { gb_d[6] }]
set_property -dict { PACKAGE_PIN A12   IOSTANDARD LVCMOS33 } [get_ports { gb_d[7] }]

## Board connector ports
#set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports disp_sdo]
set_property -dict { PACKAGE_PIN B5    IOSTANDARD LVCMOS33 } [get_ports { disp_sdi }]
set_property -dict { PACKAGE_PIN A4    IOSTANDARD LVCMOS33 } [get_ports disp_sclk]
set_property -dict { PACKAGE_PIN C4    IOSTANDARD LVCMOS33 } [get_ports disp_cs]
set_property -dict { PACKAGE_PIN A3    IOSTANDARD LVCMOS33 } [get_ports disp_rst]
set_property -dict { PACKAGE_PIN B3    IOSTANDARD LVCMOS33 } [get_ports {disp_r[4]}]
set_property -dict { PACKAGE_PIN A2    IOSTANDARD LVCMOS33 } [get_ports {disp_r[3]}]
set_property -dict { PACKAGE_PIN C3    IOSTANDARD LVCMOS33 } [get_ports {disp_r[2]}]
set_property -dict { PACKAGE_PIN B2    IOSTANDARD LVCMOS33 } [get_ports {disp_r[1]}]
set_property -dict { PACKAGE_PIN B1    IOSTANDARD LVCMOS33 } [get_ports {disp_r[0]}]
set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33 } [get_ports {disp_g[5]}]
set_property -dict { PACKAGE_PIN C1    IOSTANDARD LVCMOS33 } [get_ports {disp_g[4]}]
set_property -dict { PACKAGE_PIN D2    IOSTANDARD LVCMOS33 } [get_ports {disp_g[3]}]
set_property -dict { PACKAGE_PIN D1    IOSTANDARD LVCMOS33 } [get_ports {disp_g[2]}]
set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports {disp_g[1]}]
set_property -dict { PACKAGE_PIN F2    IOSTANDARD LVCMOS33 } [get_ports {disp_g[0]}]
set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33 } [get_ports {disp_b[4]}]
set_property -dict { PACKAGE_PIN H1    IOSTANDARD LVCMOS33 } [get_ports {disp_b[3]}]
set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports {disp_b[2]}]
set_property -dict { PACKAGE_PIN J1    IOSTANDARD LVCMOS33 } [get_ports {disp_b[1]}]
set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports {disp_b[0]}]
set_property -dict { PACKAGE_PIN L3    IOSTANDARD LVCMOS33 } [get_ports disp_de]
set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports disp_pclk]
set_property -dict { PACKAGE_PIN L2    IOSTANDARD LVCMOS33 } [get_ports disp_hs]
set_property -dict { PACKAGE_PIN M1    IOSTANDARD LVCMOS33 } [get_ports disp_vs]
set_property -dict { PACKAGE_PIN M2    IOSTANDARD LVCMOS33 } [get_ports { joy_b }]
set_property -dict { PACKAGE_PIN N1    IOSTANDARD LVCMOS33 } [get_ports { joy_a }]
set_property -dict { PACKAGE_PIN M3    IOSTANDARD LVCMOS33 } [get_ports { joy_start }]
set_property -dict { PACKAGE_PIN P2    IOSTANDARD LVCMOS33 } [get_ports { joy_select }]
set_property -dict { PACKAGE_PIN P3    IOSTANDARD LVCMOS33 } [get_ports { joy_right }]
set_property -dict { PACKAGE_PIN N4    IOSTANDARD LVCMOS33 } [get_ports { joy_up }]
set_property -dict { PACKAGE_PIN P4    IOSTANDARD LVCMOS33 } [get_ports { joy_down }]
set_property -dict { PACKAGE_PIN P5    IOSTANDARD LVCMOS33 } [get_ports { joy_left }]

## Audio
set_property -dict {PACKAGE_PIN M10 IOSTANDARD LVCMOS33} [get_ports audio_l]
set_property -dict {PACKAGE_PIN M11 IOSTANDARD LVCMOS33} [get_ports audio_r]

## Quad SPI Flash
## Note: QSPI clock can only be accessed through the STARTUPE2 primitive
set_property -dict { PACKAGE_PIN C11   IOSTANDARD LVCMOS33 } [get_ports { qspi_cs }]
set_property -dict { PACKAGE_PIN B11   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[0] }]
set_property -dict { PACKAGE_PIN B12   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[1] }]
#set_property -dict { PACKAGE_PIN D10   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[2] }]
#set_property -dict { PACKAGE_PIN C10   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[3] }]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
